### PR TITLE
fix rate limit oldest is None

### PR DESCRIPTION
**Pull request by Ed-XCF**

### CODE REVIEW

**Comment by coleifer** [comment]
I fail to see how this could occur.

**Comment by Ed-XCF** [comment]
counter[-1] may return None, float(None) will raise an error

**Comment by coleifer** [comment]
How would that happen?

**Comment by Ed-XCF** [comment]
> How would that happen? We only ever add the time to the list, and if the list is shorter than the limit we would prepend the time.

the key is expired between "len(counter)" and "counter[-1]"

**Comment by Ed-XCF** [comment]
In my case, the rate limit is "limit=1 per=5" and multiple workers are using it most every 10 seconds

**Comment by coleifer** [comment]
I was wondering if there was some kind of race but that makes sense too. I added a new lua implementation of the rate limit that should be immune to this problem:

https://github.com/coleifer/walrus/commit/7b675320bc7f5342cad0ffe58bf46bc029d6c295

I'll also go ahead and merge your change. Thanks for your persistence.

**Pull request merged**
