### PR TITLE
Modify to encode to UTF-8 to fix unicode string issues on join.

### LINKED ISSUE #48: Graph query raises UnicodeDecodeError when using unicode strings.
Looks like the string being joined into the key is using a bytestring, which causes issues on decode.

Quick script to reproduce:

```
>>> from walrus import Database
>>> from walrus.graph import Graph
>>> db = Database()
>>> graph = db.graph('foo')
>>> graph.store(s=u'subject', p=u'predicate', o=u'object')
>>> query = graph.query(p=u'predicate', o=u'object')
>>> next(query)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\site-packages\walrus\graph.py", line 146, in query
    start, end = self.keys_for_query(s, p, o)
  File "\lib\site-packages\walrus\graph.py", line 133, in keys_for_query
    return key(parts + ['']), key(parts + ['\xff'])
  File "\lib\site-packages\walrus\graph.py", line 116, in <lambda>
    key = lambda parts: '::'.join(parts)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by johndlong**
Fixes #48 

Set it to decode the \xff bytestring to UTF-8 with replacement to support joining the string with unicode strings.

Not sure if you want to fix it this way, but it resolves the issues I was running into.

### CODE REVIEW

**Comment by coleifer** [comment]
What if instead you were to encode your unicode text as UTF-8 before passing it in to the Graph? Would that solve the problem as well?

**Comment by johndlong** [comment]
Yeah, that would appear to resolve it as well.  Trying to rethink this a bit.

Would it be better to make it look/behave more like how TextFields work?  Check each s/p/o value for unicode_type and encode it to utf-8?  And then always decode back to utf-8 on any queries?

Just some background, I'm using data from TextField in the model to create some of these graphs, so I'm typically dealing with unicode by default.  I could handle the encodings before passing into the Graph, but I'm not sure if others will run into the same issues.

**Comment by coleifer** [comment]
@johndlong -- yeah, that's a good question. I waffle about it, on the one hand Redis stores bytes and it seems natural for it to require UTF-8 in the event you want to store text. On the other hand, elsewhere in walrus unicode is accepted and encoded (TextFields on models, for instance).

**Comment by johndlong** [comment]
@coleifer -- I've updated code on my end to handle the encoding prior to passing it to the Graph.  Based on that, this fix is definitely not worth merging in.

I can understand the dilemma and I'm fine with either approach really.  It might be worth keeping the issue open in case you want to add documentation and/or prevent the user from using unicode.

On a side note, could a version of walrus with the Graph get published to PyPI?

**Comment by coleifer** [comment]
I think that instead it should be the user's responsibility to send UTF-8 bytes in to the Graph, rather than have the graph calling .decode().

**Comment by johndlong** [comment]
Sorry if it came across I was proposing otherwise.  I don't disagree with that.  I'm going to go ahead and close this Pull Request.

I just wasn't sure about the related issue.  Whether it would be better to document the UTF-8 restriction in the API documentation, or potentially raise an error if someone passes in a unicode string?  (I only propose that because the UnicodeDecodeError is pretty painful to figure out).

I don't necessarily disagree with closing the issue either, just figured the error will come up with anybody else that uses unicode_literals or TextField data as the basis for the data going into the graph.

**Pull request closed without merging**
